apiVersion: v1
kind: Service
metadata:
  name: {{ include "inventory.postgres.fullname" . }}
  labels:
    {{- include "inventory.labels" . | nindent 4 }}
    {{- include "inventory.postgres.selectorLabels" . | nindent 4 }}
spec:
  type: ClusterIP
  selector:
    {{- include "inventory.postgres.selectorLabels" . | nindent 4 }}
  ports:
    - name: postgres
      port: {{ .Values.postgres.service.port }}
      targetPort: postgres
